### ISSUE TITLE
allow select/multiselect to be settable with a parameter

### ISSUE THREAD

**Issue by joachim-n** [laravel/prompts#111]
This doesn't work to dynamically choose whether a prompt is single or multi-select:

```
        $prompt_function = $data->isMultiple() ? 'multiselect' : 'select';

        $value = $prompt_function(
          label: 'Enter the ' . $data->getLabel(),
          options: $options,
        );
```

I assume it's something to do with how PHP functions are imported?

I think it would be useful if select() could take a 'multivalued' boolean parameter. multiselect() could remain as a shorthand for that.

**Comment by joachim-n** [comment]
Actually, the same with search/multisearch.

And to scope-creep this a bit, it would be nice if search could be done with a select() automatically if the passed $options parameter is a callable.

**Comment by driesvints** [comment]
Heya. Feel free to attempt a PR if you like and we can have a look at the code involved!
