### ISSUE TITLE
Can't hit enter in text input

### ISSUE THREAD

**Issue by philharmonie** [laravel/prompts#129]
### Laravel Prompts Version

0.1.17

### Laravel Version

10.48.4

### PHP Version

8.2.16

### Operating System & Version

macOS 14.2.1

### Terminal Application

phpStorm 2023.3.35

### Description

I can't hit enter to confirm a text input.
I already tried to `rm -rf vendor && composer install && composer clear-cache && composer dump-autoload` without success 

### Steps To Reproduce

Run e.g. `artisan make:controller` and enter the controller name.
When hitting enter, nothing happens.

**Comment by philharmonie** [comment]
It prints `\n` and in the default macOS the issue does not occur. But in general the enter key is working in the phpStorm terminal.

**Comment by jessarcher** [comment]
That's really strange. `\n` is the character we look for to detect an Enter keypress, so I can't think of any reason why Enter wouldn't be detected. The script I gave you emulates everything Prompts does to detect keypresses.

Can you confirm whether the issue occurs in a fresh Laravel installation?

**Comment by philharmonie** [comment]
In the meantime there is a new update for phpstorm and the issue vanished. Still weird, but for me: resolved
