### ISSUE TITLE
`multiselect` / `multisearch` helper functions are missing default hint

### ISSUE THREAD

**Issue by ExeQue** [laravel/prompts#172]
### Laravel Prompts Version

0.1.19

### Laravel Version

10.48.8

### PHP Version

8.2.8

### Operating System & Version

WSL w/ Docker Linux 5.15.153

### Terminal Application

Windows Terminal

### Description

The `func_get_args` does not include parameters with default values when using the `multiselect`/`multisearch` helper function, which causes the `$hint` parameter to be the default value of `the constructors of the respective classes which is empty.

It only returns the parameters explicitly given in the function call.

### Steps To Reproduce

1. Prompt using the `multiselect` helper function.
2. Note the missing default hint

![image](https://github.com/user-attachments/assets/1ebaa56a-5c97-4fd8-b9f0-1e6ac720ddfd)
![image](https://github.com/user-attachments/assets/d78abd56-a6ef-406d-badc-1ff7a5cb8894)

**Comment by jessarcher** [comment]
Thanks, @ExeQue!

I've created #174 to address this.
