### ISSUE TITLE
return value from search is inconsistent

### ISSUE THREAD

**Issue by jochem-blok** [laravel/prompts#173]
### Laravel Prompts Version

main

### Laravel Version

n/a

### PHP Version

8.3.9

### Operating System & Version

Debian GNU/Linux 12 (bookworm)

### Terminal Application

windows command

### Description

The answers of the search option sometimes return the key and sometimes the value. This depends on the way of entering the information.

### Steps To Reproduce

In the docs is written: 

> The closure will receive the text that has been typed by the user so far and must return an array of options. If you return an associative array then the selected option's key will be returned, otherwise its value will be returned instead.

This causes a problem. See the example below:
```php
use function Laravel\Prompts\form;


$languages = ['PHP', 'JS', 'Java', 'Python', 'C#'];

$responses = form()
    ->search('What is your language?',
        options: function (string $value) use ($languages): array {
            return array_filter($languages, static fn ($option) =>
            str_contains(strtolower($option), strtolower($value))
            );
        },
        name: 'language')
    ->submit();

print_r($responses);
```

Let me fill the form by pressing the down key twice:
![afbeelding](https://github.com/user-attachments/assets/548ef89f-f10b-47dc-8520-76a466508bec)

Now I use the search option:
![afbeelding](https://github.com/user-attachments/assets/0b0b0b1e-18ea-492d-abb4-35e078cc368b)

And I choose JS. This is the result:
![afbeelding](https://github.com/user-attachments/assets/9cf72ff5-5fab-48e6-93ad-a67775713c75)

Debugging the code I see the return is based on the filtered set. And this is no longer a list, so the key is returned.

See method: `\Laravel\Prompts\SearchPrompt::value()`.

Dynamically trying to determine what the result must be is error prone, based on the example above. Determining if the  `\Laravel\Prompts\SearchPrompt::value()` should return a key or the value should be done in the constructor. But then performance could be a problem while fetching all the data from the closure (this could be an result of a query). See the example from the docs below:
```php
$id = search(
    label: 'Search for the user that should receive the mail',
    options: fn (string $value) => strlen($value) > 0
        ? User::whereLike('name', "%{$value}%")->pluck('name', 'id')->all()
        : []
);
```

I think we must introduce an option to set the return value. This could be 3 options to be non breakable:
1. auto (current behaviour)
2. key (always return the key)
3. value (always return the value).

What do you think?

**Comment by jessarcher** [comment]
In that scenario I'd make sure the callback always returns a list by passing the filtered values through the `array_values` function:

```php
$languages = ['PHP', 'JS', 'Java', 'Python', 'C#'];

$responses = form()
    ->search('What is your language?',
        options: function (string $value) use ($languages): array {
            return array_values(array_filter($languages, static fn ($option) =>
                str_contains(strtolower($option), strtolower($value))
            ));
        },
        name: 'language')
    ->submit();
```

**Comment by jochem-blok** [comment]
Thanks for your reply! And indeed solves my issue. Probably this should be added to the docs?

**Comment by jessarcher** [comment]
I'll open a docs PR now :+1:
