### ISSUE TITLE
Unhandled carriage return as 'Enter'

### ISSUE THREAD

**Issue by Carnicero90** [laravel/prompts#176]
### Laravel Prompts Version

0.3.2

### Laravel Version

11.31.0

### PHP Version

8.3.3

### Operating System & Version

macOS 14.5

### Terminal Application

alacritty, builtin vscode terminal, etc

### Description

Whenever my terminal doesn't convert carriage return to new line (not sure why taht's happening, it seems to be caused by prompts though, for whatever reason), I am unable to submit any prompt, since \r isn't handled.

I think you could either add _icrnl_ in Terminal@setTty or submit on $key == Key::CARRIAGE_RETURN as well, maybe?

I patched via 
`    public function setTty(string $mode): void
    {
        $this->initialTtyMode ??= $this->exec('stty -g');

        $this->exec("stty $mode icrnl");
    }`
in my repo, I'm not quite sure of all the implications of this approach though.

### Steps To Reproduce

`stty -icrnl`
`php artisan make:request`
try to press enter

**Comment by jessarcher** [comment]
Hey @Carnicero90,

I started working on a PR to accept `\r` (in addition to `\n`), which seems to work with `-icrnl` set. However when I went to stage the commit (using `git add -p`) I found that `-icrnl` also broke the Enter key in git, which gave me pause. Instead of staging the hunk, it just output `^M`.

I don't think that's a reason not to accept `\r`, but I'm curious whether git's patch mode UI is also broken for you when pressing Enter?

**Comment by Carnicero90** [comment]
It does indeed, never noticed since I generally have a dedicate pane for git stuff.
Btw I think the issue may be caused by psysh use of less for pagination, whenever the process doesn't terminate gracefully. I'll try to figure out when that happens, using strace or whatever tracking tool is available in macos.
Thanks.

**Comment by Carnicero90** [comment]
Well, I would say on an almost daily basis: not a biggie though, I'm leaving here `stty sane` as a workaround/solution for whoever would run in the same issue in the future. At least in a unix env, dunno about windows.

**Comment by jessarcher** [comment]
Do you know how to replicate it? I've tried running psysh (via tinker) and then running prompts, but the Enter key still works fine.

**Comment by Carnicero90** [comment]
Sorry, I haven't been using macos almost at all recently: it doesn't seem to happen anymore, and I won't be able to replicate my previous setup/dependency chain: go figure. Thanks anyway.
