### ISSUE TITLE
documentation link broken

### ISSUE THREAD

**Issue by hardikdangar** [laravel/prompts#19]
### Laravel Prompts Version

1

### Laravel Version

10.4.1

### PHP Version

8.2

### Operating System & Version

macos 13

### Terminal Application

iterm

### Description

Currently documentation link provided is broken. it leads to 404 page. I tried to search for it but couldn't find right path or else i would have sent pull request.

### Steps To Reproduce

go to https://github.com/laravel/prompts

in official documentation section link is provided https://laravel.com/docs/prompts 

when you click the link it redirects to 404 page.

**Comment by Oleksandr-Moik** [comment]
This page is still being written. You can view it here https://github.com/laravel/docs/pull/8924

**Comment by Oleksandr-Moik** [comment]
This page is not ready yet. You can view it here https://github.com/laravel/docs/pull/8924
