### ISSUE TITLE
Accent Caracter

### ISSUE THREAD

**Issue by devajmeireles** [laravel/prompts#23]
### Laravel Prompts Version

Latest

### Laravel Version

Latest

### PHP Version

8.1.21

### Operating System & Version

macOS 13.4.1

### Terminal Application

iTerm2 3.4.19

### Description

I don't know if this is really a bug, but for cases where we have words with accents, when erasing the word, a ball symbol like this one remains in the terminal, which also affects the layout of the layout on the right:

![CleanShot 2023-08-01 at 7 15 08](https://github.com/laravel/prompts/assets/60591772/60903add-7c5e-468d-b4fb-22e239394b09)

For example: `Pagination` in Portuguese 👉  `Paginação`

![CleanShot 2023-08-01 at 7 15 44](https://github.com/laravel/prompts/assets/60591772/fd16bf12-5b12-445a-9378-8183a32085d1)

### Steps To Reproduce

Try using a word that contains accents and then delete it.

**Comment by jessarcher** [comment]
Thanks for reporting this! I've created #26 which should solve this.

**Comment by devajmeireles** [comment]
> 

You make the difference, Jess.
