### ISSUE TITLE
Multi-byte characters make the right border position incorrect

### ISSUE THREAD

**Issue by crazywhalecc** [laravel/prompts#29]
### Laravel Prompts Version

v0.1.1 (I also tested dev-main)

### Laravel Version

Independent installation of prompts

### PHP Version

8.2.8

### Operating System & Version

macOS 13.0

### Terminal Application

Terminal

### Description

When I input multi-byte characters (such as Chinese, Japanese, Emoji, etc.), the width of the border at the end changes. These multibyte characters occupy 2 spaces, but the calculation boundary may use its actual length (3 spaces).

Maybe using `mb_strwidth` to solve this?

### Steps To Reproduce

<img width="557" alt="image" src="https://github.com/laravel/prompts/assets/20330940/6e736d3f-085b-4940-974f-465435446b97">

<img width="541" alt="image" src="https://github.com/laravel/prompts/assets/20330940/0cc44630-a9d0-45ff-8727-370baf0bac58">

**Comment by jessarcher** [comment]
Hey @crazywhalecc,

TIL about `mb_strwidth`! Thank you! I've been using `mb_strlen`, which works fine for single-width multibyte characters like accents, but not emojis, etc.

I'll have a play around and hopefully get something together soon.

**Comment by tyler36** [comment]
Came across this using Japanese with Prompt `0.1.3` on WSL. 

![prompt](https://github.com/laravel/prompts/assets/7234392/2b03e20a-4e25-4829-83e5-6eba70979f0c)

**Comment by jessarcher** [comment]
Continuing the discussion over at #33
