### ISSUE TITLE
`Search` function in small width of terminal

### ISSUE THREAD

**Issue by utsavsomaiya** [laravel/prompts#3]
### Laravel Prompts Version

0.1.0

### Laravel Version

10.16.1

### PHP Version

8.2

### Operating System & Version

Linux

### Terminal Application

Terminal of vs code and simple Terminal

### Description

If I open the terminal from vs code and press the up and down arrow then it is made a new search prompt.

In my linux terminal works fine.

https://github.com/laravel/prompts/assets/96036522/c11b4730-3dde-44a3-b6ef-e729cdc70310

### Steps To Reproduce

I just install laravel application and make a simple command

**Comment by devajmeireles** [comment]
I don't know what the Laravel team thinks, but for me this isn't a problem in Prompts, or am I wrong? 🤔

**Comment by jessarcher** [comment]
The `search` and `suggest` prompts need a minimum terminal height of 8 lines. The others need at least 6 lines.

I can't solve this other than throwing an error saying to increase the terminal height or reduce the font size. I could make it interactive so they can adjust the terminal size and then press enter to continue, but I'd want to see more people having the issue before going that far.

**Comment by utsavsomaiya** [comment]
Okay, Jess Thanks..

I just want to ask something to you is Laravel using currently termwind for display the info..

Which is create a new line after info will display.. is it possible to remove the new line :

![image](https://github.com/laravel/prompts/assets/96036522/0ce9f28e-6e23-4a9d-982e-b2757894b3c3)

**Comment by utsavsomaiya** [comment]
![image](https://github.com/laravel/prompts/assets/96036522/cd461802-9d71-4c8c-a1c5-2501e41a4168)

May be this method is not capturing the new line. 😢

**Comment by jessarcher** [comment]
> I just want to ask something to you is Laravel using currently termwind for display the info..
> 
> Which is create a new line after info will display.. is it possible to remove the new line :

This shouldn't be an issue once https://github.com/laravel/framework/pull/46772 is merged because we're configuring Laravel to share its output buffer with Prompts, so they should be aware of each other's newlines.

In the meantime, you could add [this line](https://github.com/laravel/framework/pull/46772/files#diff-9c0b99959f28e3b7a54a93a4ff67818de374a378726f8ecd16fa3c3bded6a9c7R25) yourself.

**Comment by jessarcher** [comment]
I've created PR #20 to display a more helpful error message when the terminal height is too small.
