### ISSUE TITLE
Terminal Height and Width Exception

### ISSUE THREAD

**Issue by utsavsomaiya** [laravel/prompts#34]
### Laravel Prompts Version

0.1.3

### Laravel Version

10.17.0

### PHP Version

8.2

### Operating System & Version

Linux

### Terminal Application

Vs code terminal

### Description

![image](https://github.com/laravel/prompts/assets/96036522/f615ef1a-aed9-444e-b371-1359d3241710)

---
May be at this moment can we use old prompts which used in laravel 10.16!!?

### Steps To Reproduce

#3

**Comment by jessarcher** [comment]
Hi @utsavsomaiya,

Is Prompts incorrectly calculating your terminal height? From your screenshot, it looks like you have far more than the minimum 8 lines.

If you'd like to fall back to the old prompts, you can add the following to `routes/console.php`, providing whatever conditional you like:

```php
\Laravel\Prompts\Prompt::fallbackWhen(true);
```

If your system has `tput` available, you could try something like this (untested):

```php
\Laravel\Prompts\Prompt::fallbackWhen(shell_exec('tput lines') < 8);
```

**Comment by utsavsomaiya** [comment]
Thanks @jessarcher .

I just checked it. My concern doesn't like you suggested. My concern is when `tput lines` are 6. At that time can we show the old prompts?

**Comment by utsavsomaiya** [comment]
And my screenshot is captured by bigger height. So don't worry. It's works fine in my machine.

**Comment by crynobone** [comment]
I wonder if we can check for requirement when configuring Prompt to Laravel Command and fallback automatically instead of seeing an exception.

**Comment by jessarcher** [comment]
> Thank you, @jessarcher.
> 
> I just checked your suggestion, but my concern is not exactly what you suggested. My concern is when the terminal's scrollback lines are set to 6, can we still show the old prompts?

I'm unaware of a way to determine the number of scrollback lines from within the shell or PHP. The default in VS Code is 1000, so I'm curious to know why you've reduced it so drastically?

When I set the scrollback lines to 6, the prompts work fine for me in VS Code terminal. It's just the number of visible lines that impact it (i.e. the height), which can be determined in a few ways:

```sh
tput lines

stty size

echo $LINES # This won't work inside PHP because it's a shell variable not an environment variable
```

![image](https://github.com/laravel/prompts/assets/4977161/3fecbfb7-ba2a-473e-b8e4-c47d62cecee5)

> This becomes an issue because sometimes I unknowingly start the database seeding in my VS Code terminal and then close it to continue with my work. Later, when I check again, it throws an exception because the terminal closed, and I missed the error.
> 
> Is there a way to address this?

I'm not sure what you mean. How do you unknowingly start database seeding? And how are Prompts involved?

I have tried adding a prompt to `DatabaseSeeder.php` and running `sleep 5 && php artisan db:seed` before closing the terminal. When I open the terminal after 5 seconds, the prompt has displayed fine, as long as the terminal was at least 8 lines tall before it was closed.

![image](https://github.com/laravel/prompts/assets/4977161/6d3a028a-da8d-46f4-ac1b-fc5b3bdc1aba)

I can look at making Laravel automatically fall back to Symfony when the terminal is less than 8 lines, but I'd like to understand a bit more about your issue first.

**Comment by utsavsomaiya** [comment]
![image](https://github.com/laravel/prompts/assets/96036522/8ba66c0f-9641-4a70-80f6-b84afa124663)

As I closed my vs code terminal height will be set to the 6 right?

Then at that time my databaseseeder is running but `outro` function is remaining to called. See the height will 6 and give me exceptions. But my old one is 8.

So I need no exception but the give me old laravel prompts. And I also put the `fallback` in console but may be it is not running.

![image](https://github.com/laravel/prompts/assets/96036522/75056f40-d456-47e1-849e-fbaef8c79970)

**Comment by utsavsomaiya** [comment]
Can I change the color of the font?

![image](https://github.com/laravel/prompts/assets/96036522/47401482-2e9e-45e6-849f-87d566c83ea1)

**Comment by jessarcher** [comment]
> As I closed my vs code terminal height will be set to the 6 right?

In my tests the terminal height reported to Prompts is whatever height the terminal was before it was closed.
 
> Then at that time my databaseseeder is running but `outro` function is remaining to called. See the height will 6 and give me exceptions. But my old one is 8.

Could you perhaps create a minimal reproduction repo and steps? It sounds like you've customised your database seeder a fair bit. When I test locally with a fresh Laravel installation in a fresh VS Code installation, I can't replicate the issue unless I resize the terminal height to be less than 8 lines.
 
> So I need no exception but the give me old laravel prompts. And I also put the `fallback` in console but may be it is not running.
> 
> ![image](https://user-images.githubusercontent.com/96036522/258421833-75056f40-d456-47e1-849e-fbaef8c79970.png)

This should be `true`, not `false`:

```php
Prompt::fallbackWhen(true);
```

**Comment by utsavsomaiya** [comment]
Yeah.. it works. Thanks jess. 😊 
But sometimes I just close the terminal background process is give me failure but after set it true then its works fine.

Thanks.. It's out of my knowledge.

**Comment by Abdalmalekshd** [comment]
can you tell what is the solution please,because the images won't upload

**Comment by utsavsomaiya** [comment]
https://github.com/laravel/prompts/issues/34#issuecomment-1665206680
