### ISSUE TITLE
Usage of colors makes the right border position incorrect

### ISSUE THREAD

**Issue by sc85** [laravel/prompts#45]
### Laravel Prompts Version

0.1.14

### Laravel Version

10.18.0

### PHP Version

8.1.14

### Operating System & Version

macOS 13.5

### Terminal Application

Terminal

### Description

When using a color within options the right border is not aligned but shifted to the left.
So far, I noticed the issue with select, multiselect and search.
This issue seems somehow similar to #29.

As visible in the screenshot the number of chars the border is shifted seems to be related to the number of chars used to identify the color.

![image](https://github.com/laravel/prompts/assets/4824890/0ab306cb-18c7-4bcc-b8d5-fe1723f62be2)

P.S.: I love the new prompts 😍 

### Steps To Reproduce

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

use function Laravel\Prompts\select;

class Dummy extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'dummy';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Dummy command';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle(): int
    {
        select(
            'See the issue?',
            [
                'yes' => '<bg=green>yes</>',
                'no' => '<bg=red>no</>',
                'maybe' => '<bg=yellow>maybe</>',
                'dontKnow' => 'don\'t know',
            ],
        );
        return Command::SUCCESS;
    }
}
```

**Comment by jessarcher** [comment]
Thanks, @devajmeireles!
