### ISSUE TITLE
Add help text or expected input to multi-select prompts

### ISSUE THREAD

**Issue by afolson** [laravel/prompts#48]
When presented with a multi-select prompt, it's not clear what input is expected in order to select options:

<img width="467" alt="Screenshot 2023-08-11 at 11 00 14 PM" src="https://github.com/laravel/prompts/assets/2797769/0228222c-86b8-4f00-829b-840d61dd6552">

I looked in the [docs](https://laravel.com/docs/10.x/prompts#multiselect) but didn't see any info there. Ultimately I ended up on the issue tracker where another user had the same issue: https://github.com/laravel/prompts/issues/41 I tried various key combinations (y/n, 1/0, return, tab/ctrl/shift/alt/cmd combinations) but spacebar wasn't one of them 🫣. A line that says "Use spacebar to select options" or a mention in the docs (or both) would definitely help here.

@jessarcher You mentioned the possibility of adding this feature https://github.com/laravel/prompts/issues/41#issuecomment-1666808775 so I figured I'd open up an issue to +1 the idea.

**Comment by devajmeireles** [comment]
> When presented with a multi-select prompt, it's not clear what input is expected in order to select options:
> 
> <img alt="Screenshot 2023-08-11 at 11 00 14 PM" width="467" src="https://user-images.githubusercontent.com/2797769/260195222-0228222c-86b8-4f00-829b-840d61dd6552.png">
> I looked in the [docs](https://laravel.com/docs/10.x/prompts#multiselect) but didn't see any info there. Ultimately I ended up on the issue tracker where another user had the same issue: #41 I tried various key combinations (y/n, 1/0, return, tab/ctrl/shift/alt/cmd combinations) but spacebar wasn't one of them 🫣. A line that says "Use spacebar to select options" or a mention in the docs (or both) would definitely help here.
> 
> @jessarcher You mentioned the possibility of adding this feature [#41 (comment)](https://github.com/laravel/prompts/issues/41#issuecomment-1666808775) so I figured I'd open up an issue to +1 the idea.

Perhaps you are looking for something [like that](https://github.com/laravel/prompts/pull/44)?

**Comment by jessarcher** [comment]
Hey, @afolson!

Thanks for letting me know. Once #44 is merged, I'll PR the installer to add hint text along the lines of "Press the spacebar to select options."

We could also make the `y`/`n` keys select and de-select, as those keys are currently unbound for the multi-select prompt.

**Comment by jessarcher** [comment]
PR #50 adds a hint to `multiselect` prompts by default :slightly_smiling_face:
