### ISSUE TITLE
Feature Request: Progress Bar

### ISSUE THREAD

**Issue by adrianb93** [laravel/prompts#51]
Amazing work, Jess. `laravel/prompts` is mint 👌

I would love to suggest a progress bar component.

It's not really an input, but it is something you could cancel, or it could be combined with a text input - for example entering a URL to download from.

For example:

- Label
- Cancelled state
- Customise the display value for the numerator/denominator
- Pending mode _(like a loading spinner variant if progress is unknowable)_
- Parallel progress bars? - or maybe parallel output could be a seperate feature of its own
- Maybe `Http` download support, i.e. sugar for `Http::sink('/path/to/file')->withOptions(['progress' => ...])->get($url)`

**Comment by devajmeireles** [comment]
> 

Particularly I think the idea of progress bar is very old. Why not use the [spin](https://github.com/laravel/prompts/blob/main/playground/spin.php) instead? It is enough that when a process finishes, you call another spin, sequentially:

![CleanShot 2023-08-16 at 11 38 26](https://github.com/laravel/prompts/assets/60591772/a6db8a65-dc80-455a-815d-5c57a1ca4e21)

Perhaps something like that would be awesome. I will try to suggest:

```php
spin(fn () => sleep(3), 'Installing dependencies...')
    ->then(fn () => sleep(3), 'Preparing environment...')
    ->then(fn () => sleep(3), 'Finishing up...');
```

**Comment by adrianb93** [comment]
> Why not use the [spin](https://github.com/laravel/prompts/blob/main/playground/spin.php) instead?

I had no idea that spin was in here. It's not documented.

> Particularly I think the idea of progress bar is very old.

Subjective. For most cases I'd agree. For my needs: 

- I have a large file download that I'd prefer to see progress, time elapsed, and time remaining for. 
- I've also worked on import commands that work through many files (an unknown amount) where you'd want to know the progress.

I also think a progress component would look cool for job batches as a use-case for the framework.
