### ISSUE TITLE
No output after `Artisan::call()` command

### ISSUE THREAD

**Issue by syntafin** [laravel/prompts#74]
### Laravel Prompts Version

0.1.7

### Laravel Version

10.23.1

### PHP Version

8,2.10

### Operating System & Version

Arch Linux (Stable Kernel)/Ubuntu 22.04

### Terminal Application

ZSH

### Description

Good day,
asked on Discord yesterday and got said to open an issue.

I migrated the Migration Console Command in my application to Prompts, the informational message ``intro`` is shown, and the ``confirm`` question too, but after this nothing else, until the command is done, for local environment this does work, but on staging/production it doesnt, as some parts need manual input there.

Maybe this video shows what I mean:
https://github.com/laravel/prompts/assets/695535/0fb409e9-4b61-4f7a-bb65-eeae6728c929

Even if I remove the ``spin`` (I just tested something with it, as it is not documented), nothing else is shown, the full code of my migration can be found in this Gist:
https://gist.github.com/syntafin/dc028e3d9a6863dcef5d26a0bbc9ea96

Last shown prompt is in Line 50-56, everything else doesnt appear (migration still completes on local).

### Steps To Reproduce

- Use Laravel Prompts
- After 3 Prompts, everything else is skipped

**Comment by jessarcher** [comment]
Hi @syntafin,

I've replicated this and found that it's the `Artisan::call()` commands that are causing it.

If you change them to `$this->call()` then it works fine.

This is how it's documented to call commands from other commands: https://laravel.com/docs/10.x/artisan#calling-commands-from-other-commands

The `Artisan::call()` method is only documented for calling Artisan commands outside of the CLI: https://laravel.com/docs/10.x/artisan#programmatically-executing-commands

Still, I don't see any reason why `Artisan::call()` shouldn't work. I haven't had a chance to dig it fully, but it seems that `Artisan::call()` doesn't output anything to the CLI, so it's probably changing the `OutputBuffer` on Prompts and then not restoring it afterwards.

I'll leave this open to investigate properly when I get a chance.

**Comment by syntafin** [comment]
Thanks for the info! I will change it and try it again.

**Comment by jessarcher** [comment]
Hey @syntafin, did this solve it for you?

I have some ideas on how to make `Artisan::call()` handle this scenario, but I'm not sure whether I can justify spending time on it.

Just to document what I'm thinking (mostly for my own benefit):
1. Publicly expose the `output` method on Prompts
2. In both of Laravel's `call` methods, cache the current output buffer and then restore it afterwards, rather than relying on the `$this->output` property being correctly set in the command.

This should make things a bit more resilient, but it would need to be staged with a major version bump so that Laravel can safely depend on the new functionality being available.

**Comment by syntafin** [comment]
Yes I was able to solve it :) .

**Comment by syntafin** [comment]
I just adjusted it how Jess explained it, for example:

```
        $this->call('migrate:fresh', [
            '--force' => true,
            '--quiet' => true,
        ]);
```

**Comment by jessarcher** [comment]
@rforced When using `$this->call()`, any output is sent directly to the terminal, and only the exit code is returned.

If you want to capture the output instead, you'd probably need to do something like this in the parent command:

```php
public function handle()
{
    $output = new \Symfony\Component\Console\Output\BufferedOutput();

    $this->runCommand('other-command', [], $output);

    dump($output->fetch());
}
```

**Comment by 1e4** [comment]
> Hi [@syntafin](https://github.com/syntafin),
> 
> I've replicated this and found that it's the `Artisan::call()` commands that are causing it.
> 
> If you change them to `$this->call()` then it works fine.
> 
> This is how it's documented to call commands from other commands: https://laravel.com/docs/10.x/artisan#calling-commands-from-other-commands
> 
> The `Artisan::call()` method is only documented for calling Artisan commands outside of the CLI: https://laravel.com/docs/10.x/artisan#programmatically-executing-commands
> 
> Still, I don't see any reason why `Artisan::call()` shouldn't work. I haven't had a chance to dig it fully, but it seems that `Artisan::call()` doesn't output anything to the CLI, so it's probably changing the `OutputBuffer` on Prompts and then not restoring it afterwards.
> 
> I'll leave this open to investigate properly when I get a chance.

I still have this issue on a project and isolated it down and found this ticket. No matter what I try the input seems to bug out after calling `call()` or `callSilent()`. I have tried with `--quiet` and `--force` but the output still has issues.

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

use function Laravel\Prompts\text;

class PromptIssue extends Command
{

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:prompt-issue';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        \Laravel\Prompts\info('Prompt issue');

        $this->callSilent('migrate:fresh');

        // This doesn't show
        text(
            label: 'A text field'
        );
    }
}

```

This is on a completely fresh Laravel install `v12.3.0` and prompts `v0.3.5`

```json
{
    "$schema": "https://getcomposer.org/schema.json",
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": [
        "laravel",
        "framework"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.2",
        "laravel/framework": "^12.0",
        "laravel/prompts": "^0.3.5",
        "laravel/tinker": "^2.10.1"
    },
    "require-dev": {
        "fakerphp/faker": "^1.23",
        "laravel/pail": "^1.2.2",
        "laravel/pint": "^1.13",
        "laravel/sail": "^1.41",
        "mockery/mockery": "^1.6",
        "nunomaduro/collision": "^8.6",
        "pestphp/pest": "^3.7",
        "pestphp/pest-plugin-laravel": "^3.1"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi",
            "@php -r \"file_exists('database/database.sqlite') || touch('database/database.sqlite');\"",
            "@php artisan migrate --graceful --ansi"
        ],
        "dev": "npx concurrently -c \"#93c5fd,#c4b5fd,#fdba74\" \"php artisan serve\" \"php artisan queue:listen --tries=1\" \"npm run dev\" --names='server,queue,vite'"
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

**Comment by syntafin** [comment]
What is your environment @1e4 ? If you are not on local, you can't use ``migrate:fresh`` without ``--force``

**Comment by 1e4** [comment]
> What is your environment @1e4 ? If you are not on local, you can't use ``migrate:fresh`` without ``--force``

Yes I mentioned that I have already tried force. 

The problem isn't that migrations fail. If that was the case then I wouldn't be posting here. 

The problem is in the example I gave, promps inputs won't work properly after calling call() or callSilent()
