### ISSUE TITLE
Allow spinners to be marked as "done" and persist in the UI.

### ISSUE THREAD

**Issue by danmatthews** [laravel/prompts#89]
When running a task with multiple spinners that are over with particularly quickly, only one spinner instance is shown, but the `message:` argument changes:

![CleanShot 2023-09-27 at 11 11 10](https://github.com/laravel/prompts/assets/149426/05b1c311-24d2-42ef-9005-9e376546585b)

This is great, but if multiple tasks run quickly, the spinner simply appears to keep the text from the first instance that was around long enough to render the message:

![CleanShot 2023-09-27 at 11 12 41](https://github.com/laravel/prompts/assets/149426/8ea12fec-73c6-44d6-a48d-fa5f09374eb2)

Of course, you can add `info` calls to intersperse them:

![CleanShot 2023-09-27 at 11 14 32](https://github.com/laravel/prompts/assets/149426/22ed2c84-56db-4955-8964-0dc384f4814a)

But the spinner disappears and just leaves the info messages in one big "dump".

## Suggestion: Persistent / Completed spinner.

When a spinner completes it's callback, the spinner persists in the UI, but with a checkmark next to it, or, if it failed, a red cross?

This way, you get: predictable output for tasks and can see previous completions.

I would suggest a `persist` argument to the class:

```
spin(
  callback: fn () => $this->doSomething(),
  message: 'Calling the API',
  persist: true,
);
```

Please excuse the bad photoshop next...

<img width="762" alt="CleanShot 2023-09-27 at 11 28 45@2x" src="https://github.com/laravel/prompts/assets/149426/b8f89890-a4b5-4431-a63c-fe1bd5f5180c">

Something like this? 

Would love to know your thoughts.

**Comment by danmatthews** [comment]
Just another quick addition to this:

The ability to change the message yourself when the task is complete would be super handy too, for example, we use `spin` in our deployment script, which has a few stages.

<img width="380" alt="CleanShot 2023-09-27 at 17 02 07@2x" src="https://github.com/laravel/prompts/assets/149426/88bf4488-9ba1-4ea8-b0d7-8c2717d85632">

It would be great if we could change this to something custom like "Assets Packaged!" etc.

**Comment by driesvints** [comment]
Hi all. I think for this one that the discussion is best continued in a PR. Feel free to send one in which we can have a look at, thanks.
