### ISSUE TITLE
Number 0 key in text field causes 'Uninitialized string offset 0' exemption in TypedValue.php

### ISSUE THREAD

**Issue by stevenjweirstreet** [laravel/prompts#94]
### Laravel Prompts Version

0.1.11

### Laravel Version

8.83.27

### PHP Version

8.2.11

### Operating System & Version

macOS 13.0

### Terminal Application

Warp

### Description

When using a `text()` field, in Laravel 8 at least, when the zero number key is pressed, it is causing an ErrorException as shown below here `vendor/laravel/prompts/src/Concerns/TypedValue.php:43`. This is with or without other alpha-numeric characters, as soon as zero is pressed, the exception fires.

You can paste 0's in, it's just on keypress.

<img width="1395" alt="image" src="https://github.com/laravel/prompts/assets/89396299/f1f9c873-0918-4f68-8e07-a40de1af0712">

### Steps To Reproduce

When entering text into a `text()` field using a keyboard, not pasting, press the zero number key and exception fires.

**Comment by crynobone** [comment]
Prompts doesn't support Laravel 8. It should only be used with Laravel 10.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by stevenjweirstreet** [comment]
Thanks for replying. We're on an upgrade path, so as soon as we're at v10, I'll be making use of this package. Thank you!
