### ISSUE TITLE
support anticipate UI like text()

### ISSUE THREAD

**Issue by SocolaDaiCa** [laravel/prompts#96]
Could you create method anticipate() with UI beaulty like text() function?
Thank you very much
![image](https://github.com/laravel/prompts/assets/18243451/dafecbc8-b762-4906-83dd-6da298404312)
![image](https://github.com/laravel/prompts/assets/18243451/00531a2a-8a73-42df-b5dd-3113d5b6f818)

**Comment by jessarcher** [comment]
Hi @SocolaDaiCa,

We have the `suggest` prompt for this.

Docs at https://laravel.com/docs/10.x/prompts#suggest

**Comment by SocolaDaiCa** [comment]
@jessarcher

when I use `anticipate` I cant type and `tab` to autocomplete, after that I cant type anymore, final enter to end

but `suggest` I only can type to search, after that select on drodown

Could you support press tab to fill search to input and I cant type anymore

**Comment by jessarcher** [comment]
> when I use `anticipate` I cant type and `tab` to autocomplete, after that I cant type anymore, final enter to end

With `anticipate` I am able to continue typing after using `Tab` to select a match.

> but `suggest` I only can type to search, after that select on drodown
> 
> Could you support press tab to fill search to input after that I cant type anymore

`suggest` already supports the `Tab` key to cycle through the matches.

Both prompts allow you to submit arbitrary text or use the tab key to select a matching option. The only real differences with the `suggest` prompt are that the matches are case-insensitive, and you can't select a suggestion and then continue typing afterwards.

What is the use case you are solving?

**Comment by SocolaDaiCa** [comment]
@jessarcher yup, I want select a suggestion and then continue typing afterwards like `anticipate` but I love UI of laravel prompts.
That's all
